### ISSUE TITLE
Menu Museeks > About don't trigger anything.

### ISSUE THREAD

**Issue by cyranodev** [martpie/museeks#585]
Hi people! Thanks for this awesome app, it's the second time I try it and I'm so glad to see the improvements.

I got version. 0.11.5 deb package installed on Elementary OS Hera 5.1.7  (built on Ubuntu 18.04.4 LTS), and when I click at menu option **Museeks > About**, nothing happens.

The About session within the Config screen works fine, as does the check updates button.

**Comment by martpie** [comment]
Hoi! 

Thank you for the feedback! I will try to boot a Linux VM to see what is going on :)

**Comment by martpie** [comment]
Is it still the case on Museeks 0.12 ? I suspect it should be fixed

**Comment by cyranowebdev** [comment]
The issue remains the same, unfortunately. Just updated the OS and then Museeks, behaviour is still the same. :/

**Comment by martpie** [comment]
This is fixed with Tauri :]
