### ISSUE TITLE
Can't start development with vite: Unable to find Electron app

### ISSUE THREAD

**Issue by dipras** [martpie/museeks#681]
When i tried to start the development enviroment, i got this error
![image](https://github.com/martpie/museeks/assets/51155424/0f7d5f3b-51e0-42a2-bfe7-939c49356a5d)
But the error is not showing when i build it instead

**Comment by martpie** [comment]
I have just updated the readme so it's more clear, but the way to start the app is the following:

for dev mode:
- `yarn dev`
- `yarn museeks:debug` (in another terminal)
for prod mode:
- `yarn build`
- `yarn museeks`

Happy hacking :)

**Comment by dipras** [comment]
Yeah, I have also tried to run it using the "yarn dev" but I still get the error
![Screenshot_20230614_141204](https://github.com/martpie/museeks/assets/51155424/1672b476-0416-4cd5-b008-fb392a55feed)

it seems like vite-plugin tried to execute "dist/main/entrypoint.js" before finish the job

**Comment by martpie** [comment]
I know there is a race condition somewhere, but at least on my setup, vite then catches up and restarts Electron, let me have a closer look.

**Comment by dipras** [comment]
Ah yeah, there is race condition in in vite-plugin-electron
I tried to look into library and i found that they execute `startup()` before waited promise
![image](https://github.com/martpie/museeks/assets/51155424/bd6dc9b1-2618-44c8-8dd9-581daccbef21)

**Comment by martpie** [comment]
I can reproduce on Ubuntu, looking for a fix. In the meantime, you can just `yarn build && yarn museeks`

**Comment by dipras** [comment]
I wondered why they doesn't use promise.
I tried to implemanting promises,
![image](https://github.com/martpie/museeks/assets/51155424/9b8161ed-176d-42c0-bdad-f97c499c6d26)

but it seem the build function from vite doesn't use promise aswell for waiting build
 
![image](https://github.com/martpie/museeks/assets/51155424/cb3ed313-205e-497d-aece-531007a2468e)

As you can see, my message show up before the build progress although i used promise

**Comment by dipras** [comment]
> I can reproduce on Ubuntu, looking for a fix. In the meantime, you can just `yarn build && yarn museeks`

Nah it's too pain we must rebuild it from scrath every time we make a change, for now i can solve it by adding a time out to make startup waited so the build will finished before it's executed
![image](https://github.com/martpie/museeks/assets/51155424/8b7ab2b9-5cae-42c8-b584-c94de4475fec)

**Comment by martpie** [comment]
https://github.com/martpie/museeks/pull/682 is changing the build system (still Vite under the hood), but we're stuck on https://github.com/electron/forge/issues/3208 not being released.

**Comment by dipras** [comment]
> #682 is changing the build system (still Vite under the hood), but we're stuck on [electron/forge#3208](https://github.com/electron/forge/issues/3208) not being released.

Oh yeah, that's great. Can't we just install it directly from github like in [this article](https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub)?

**Comment by martpie** [comment]
It's a bit tricky because `electron-forge`  uses a monorepo, and I don't think installing from GitHub work well with those

**Comment by martpie** [comment]
should be fixed on master, thanks again for flagging it out :)
